site_name: Was man nicht in einem DaF-Kurs gelernt hat
theme:
  name: material
  language: de

plugins:
  - search
  - meta
  - blog

nav:
  - Blog:
      - blog/index.md
  - index.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences