authors:
  ff:
    name: Felix Fuchs        # Author name
    description: Truble Maker # Author description
    avatar: https://github.com/original-trublemaker.png         # Author avatar
    slug: (TBD)           # Author profile slug
    url: https://github.com/original-trublemaker            # Author website URL